//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.17929
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualHG {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualHG.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   VisualHG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mercurial source contol provider. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZPHPJZE3Z1PRAIJ8M2MKE3PDEDPQI1DRCQM1I8DJD1E0MKQ0I2MAC8PZKHH9JRMIK9QHC9ZZP8I8RMCEIQC3QPA1P2Z1M0ZHQZI8M2QZRAPZJCPCD0KAJ0IAZIDIH3Q1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _500 {
            get {
                object obj = ResourceManager.GetObject("500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _501 {
            get {
                object obj = ResourceManager.GetObject("501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Press Cancel to cancel this OnApply.  OK to continue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplyProviderOptions {
            get {
                return ResourceManager.GetString("ApplyProviderOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HG pending changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HGPendingChangesToolWindowCaption {
            get {
                return ResourceManager.GetString("HGPendingChangesToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualHG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file {0} you are trying to edit is read only on disk. Do you want do make the file writable so you can continue editing it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QEQS_EditUncontrolledReadOnly {
            get {
                return ResourceManager.GetString("QEQS_EditUncontrolledReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checked in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_CheckedIn {
            get {
                return ResourceManager.GetString("Status_CheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checked out by you に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_CheckedOut {
            get {
                return ResourceManager.GetString("Status_CheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pending add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_PendingAdd {
            get {
                return ResourceManager.GetString("Status_PendingAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file {0} you are going to delete is a source controlled file. Are you sure you want to continue and delete this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TPD_DeleteControlledFile {
            get {
                return ResourceManager.GetString("TPD_DeleteControlledFile", resourceCulture);
            }
        }
    }
}
